### ISSUE TITLE
TLS 1.2 for one.com not working on older OS

### ISSUE THREAD

**Issue by mooock** [morhans/win-acme_dns_one.com#1]
It might be a good idea to add some minimum requirements to the script for one.com. the script requires some higher ciphers then a server 2012R2 has. I received Schannel errors on the rest call, and from what i see on SSL labs, it might be because One.com requires newer cipher suites that comes with server 2016 from my reading.

**Comment by morhans** [comment]
Thanks for the comment. Only tested it on WS2019 and WS2022 with no issues. So that goes with your observation I'll make a notion about possible web cipher issues with older versions.
